name: manzana_verde_reto
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/perfil.png
    - assets/images/circular_barra.png
    - assets/images/switch_boton.png
    - assets/images/configuracion.png
    - assets/images/almuerzo.png
    - assets/images/cena.png
    - assets/images/media_manana.png
    - assets/images/media_tarde.png
    - assets/images/corazon.png
    - assets/images/lunch_comida.png
    - assets/images/pack.png
    - assets/jsons/daysOrdered.json
    - assets/jsons/routineInformation_tuesday.json
    - assets/jsons/routineInformation_friday.json
    - assets/jsons/routineInformation_monday.json
    - assets/jsons/routineInformation_wednesday.json
    - assets/jsons/routineInformation_thursday.json
    - assets/images/comida_one.png
    - assets/images/comida_two.png
    - assets/jsons/lunchs_monday.json
    - assets/jsons/lunchs_thursday.json
    - assets/jsons/foodDetail.json
    - assets/jsons/foodDetail_two.json
    - assets/jsons/foodDetail_three.json
    - assets/jsons/foodDetail_four.json
    
